added moco directory variable

diff --git a/moco b/moco
--- a/moco
+++ b/moco
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 # syntax: moco <amount> <from> {<to>}
 
+MOCO_DIR=/home/besnn/moco
+
 GREEN='\033[1;32m'
 RED='\033[1;31m'
 YELLOW='\033[1;33m'
@@ -34,7 +36,7 @@ case $1 in
 			exit 1;;
 		"give"|"find")
 			if [[ $2 ]]; then
-				grep -iE "$2" utils/.help || (echo -e $RED"Couldn't find currency. Sorry.\n"$RESET_COLOR 1>&2 && exit 1)
+				grep -iE "$2" $MOCO_DIR/utils/.help || (echo -e $RED"Couldn't find currency. Sorry.\n"$RESET_COLOR 1>&2 && exit 1)
 				echo
 			exit 0
 			fi
